version: '3.8'
services:
  dapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: wrakash/dapp-backend:latest
    container_name: dapp-backend-app
    ports:
      - 3008:3008
    env_file:
      - .env